# net disk related
NAS_MODE: "GLUSTER"
HOSTPATH_HOST: "/nfs"
HOSTPATH_CONTAINER: "/nfs/hostpath"
HOSTPATH_GB: "1000"
GLUSTER_NAME: "gdistvol"
GLUSTER_IP: "2.2.2.1,2.2.2.2,2.2.2.3,2.2.2.4"
GLUSTER_HOST: "/nfs/gdv"
GLUSTER_CONTAINER: "/nfs/gdv"
GLUSTER_GB: "1000"
NFS_HOST: "/nfs/nvme"
NFS_CONTAINER: "/nfs/nvme"
NFS_SERVER: "2.2.2.91"
NFS_PATH: "/mnt/mnt-nvme-lv"
NFS_GB: "1000"

# web app
FLASK_PORT: "30050"
FLASK_DEBUG: "1"
FLASK_APP: "main.py"

# Jupyter notebook
JUPYTER_UID: "1000"
JUPYTER_GID: "1000"
JUPYTER_PORT: "30088"

# Other Ports
TENSORBOARD_PORT: "30060"
NGINX_PORT: "30080"
KUBEBOARD_PORT: "8001"

