# net disk related
SHARED_HOST: "/home/ai"
HOSTPATH_CONTAINER: "hostpath"
GLUSTER_CONTAINER: "gluster"
NFS_CONTAINER: "nfs"
CEPH_CONTAINER: "cephfs"

# web app
FLASK_DEBUG: "1"
FLASK_APP: "main.py"
FLASK_DB: '/home/ai/db/sqlite3.db'

# Jupyter notebook
JUPYTER_UID: "1000"
JUPYTER_GID: "1000"

# NETWORKING
FLASK_PORT: "5000"
TENSORBOARD_PORT: "30060"
JUPYTER_PORT: "30088"
