# net disk related
NAS_MODE: "GLUSTER"
HOSTPATH_ENABLE: "1"
HOSTPATH_HOST: "/mnt/gnfs"
HOSTPATH_CONTAINER: "/mnt/gnfs"
HOSTPATH_GB: "1000"
GLUSTER_ENABLE: "0"
GLUSTER_NAME: "gdistvol"
GLUSTER_IP: "2.2.2.1,2.2.2.2,2.2.2.3,2.2.2.4"
GLUSTER_HOST: "/mnt/gnfs"
GLUSTER_CONTAINER: "/mnt/gnfs"
GLUSTER_GB: "1000"
NFS_ENABLE: "0"
NFS_HOST: "/mnt/gnfs"
NFS_CONTAINER: "/mnt/gnfs"
NFS_SERVER: "2.2.2.91"
NFS_PATH: "/mnt/mnt-nvme-lv"
NFS_GB: "1000"

# web app
FLASK_DEBUG: "1"
FLASK_APP: "main.py"
FLASK_DB: '/home/ai/db/sqlite3.db'

# Jupyter notebook
JUPYTER_UID: "1000"
JUPYTER_GID: "1000"

# Ports
FLASK_PORT: "5000"
KUBEBOARD_PORT: "8001"
TENSORBOARD_PORT: "30060"
NGINX_PORT: "30080"
JUPYTER_PORT: "30088"
