apiVersion: v1
kind: PersistentVolume
metadata:
  name: tf-gpv
spec:
  capacity:
    storage: 2000Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "gdistvol"
    readOnly: false
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tf-gpvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 180Gi
