apiVersion: v1
kind: PersistentVolume
metadata:
  name: mnt-pv
spec:
  capacity:
    storage: 2000Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: mnt
  hostPath:
    path: "/nfs/nvme"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mnt-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 180Gi
  storageClassName: mnt
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glusterfs-cluster
subsets:
- addresses:
  - ip: 2.2.2.1
  ports:
  - port: 1
---
kind: Service
apiVersion: v1
metadata:
  name: glusterfs-cluster
spec:
  ports:
  - port: 1
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: gluster-pv
spec:
  capacity:
    storage: 2000Gi
  accessModes:
  - ReadWriteMany
  glusterfs:
    endpoints: "glusterfs-cluster"
    path: "gdistvol"
    readOnly: false
  storageClassName: gluster
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: gluster-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 180Gi
  storageClassName: gluster
