apiVersion: v1
kind: PersistentVolume
metadata:
  name: tf-pv
spec:
  capacity:
    storage: 2000Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: tensorflow
  hostPath:
    path: "/nfs"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: tf-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 180Gi
  storageClassName: tensorflow
